[2024-03-19T12:46:05.905+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_2 scheduled__2023-10-02T11:43:00+00:00 [queued]>
[2024-03-19T12:46:06.250+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_2 scheduled__2023-10-02T11:43:00+00:00 [queued]>
[2024-03-19T12:46:06.282+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-19T12:46:07.990+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): task_2> on 2023-10-02 11:43:00+00:00
[2024-03-19T12:46:08.398+0000] {standard_task_runner.py:60} INFO - Started process 21201 to run task
[2024-03-19T12:46:08.637+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'task_2', 'scheduled__2023-10-02T11:43:00+00:00', '--job-id', '10058', '--raw', '--subdir', 'DAGS_FOLDER/printout.py', '--cfg-path', '/tmp/tmpjh3c0xk9']
[2024-03-19T12:46:08.760+0000] {standard_task_runner.py:88} INFO - Job 10058: Subtask task_2
[2024-03-19T12:46:14.219+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-19T12:46:14.281+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
