[2024-03-19T19:36:01.447+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.insert_dummy_data scheduled__2024-03-19T19:35:00+00:00 [queued]>
[2024-03-19T19:36:01.454+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.insert_dummy_data scheduled__2024-03-19T19:35:00+00:00 [queued]>
[2024-03-19T19:36:01.454+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T19:36:01.463+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): insert_dummy_data> on 2024-03-19 19:35:00+00:00
[2024-03-19T19:36:01.472+0000] {standard_task_runner.py:60} INFO - Started process 474 to run task
[2024-03-19T19:36:01.477+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Airflow_and_Cassandra', 'insert_dummy_data', 'scheduled__2024-03-19T19:35:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/insert_cassandra.py', '--cfg-path', '/tmp/tmpix2_kkua']
[2024-03-19T19:36:01.479+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask insert_dummy_data
[2024-03-19T19:36:01.542+0000] {task_command.py:423} INFO - Running <TaskInstance: Airflow_and_Cassandra.insert_dummy_data scheduled__2024-03-19T19:35:00+00:00 [running]> on host 52dfb58d56f6
[2024-03-19T19:36:01.591+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_and_Cassandra' AIRFLOW_CTX_TASK_ID='insert_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T19:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T19:35:00+00:00'
[2024-03-19T19:36:01.598+0000] {base.py:83} INFO - Using connection ID 'cassandra_default' for task execution.
[2024-03-19T19:36:01.600+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-03-19T19:36:01.602+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_cassandra.py", line 16, in insert_dummy_data_into_cassandra_db
    result = hook.run('select * from news.news_table;')
AttributeError: 'CassandraHook' object has no attribute 'run'
[2024-03-19T19:36:01.608+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Airflow_and_Cassandra, task_id=insert_dummy_data, execution_date=20240319T193500, start_date=20240319T193601, end_date=20240319T193601
[2024-03-19T19:36:01.615+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task insert_dummy_data ('CassandraHook' object has no attribute 'run'; 474)
[2024-03-19T19:36:01.651+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-19T19:36:01.666+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
